

 export const products = [
    {
        id:0,
        productname:"T-SHIRT WITH TAPE DETAILS",
        rating:"4.3/5",
        price:"192",
        oldprice:"240",
        discountper:20,
        category:"casual",
        collection:"new",
        brand:"zara",
        productimg:"/public/skinyjenns.png",
    },
    {
        id:1,
        productname:"SKINNY FIT JEANS",
        rating:"4.5/5",
        price:"208",
        oldprice:"260",
        discountper:20,
        category:"casual",
        collection:"new",
        brand:"zara",
        productimg:"/public/skinyjenns.png",
    },
    {
        id:2,
        productname:"CHECKERED SHIRT",
        rating:"4.1/5",
        price:"208",
        
        category:"casual",
        collection:"new",
        brand:"zara",
        productimg:"/public/5fc84f87eeac1062fbe47f49c192d4f2.png",
    },
    {
        id:3,
        productname:"SLEEVE STRIPED T-SHIRT",
        rating:"4.3/5",
        price:"130",
        oldprice:"160",
        discountper:30,
        category:"casual",
        collection:"new",
        brand:"zara",
        productimg:"/public/7cc557f42cf1d489f7cc811856b90e9f.png",
    },
    {
      id:4,
      productname:"T-SHIRT WITH TAPE DETAILS",
      rating:"4.3/5",
      price:"192",
      oldprice:"240",
      discountper:20,
      category:"casual",
      collection:"topsellings",
      brand:"zara",
      productimg:"/public/skinyjenns.png",
  },
  {
    id:5,
    productname:"T-SHIRT WITH TAPE DETAILS",
    rating:"4.3/5",
    price:"192",
    category:"casual",
    collection:"topsellings",
    brand:"zara",
    productimg:"/public/skinyjenns.png",
},
{
  id:6,
  productname:"T-SHIRT WITH TAPE DETAILS",
  rating:"4.3/5",
  price:"192",
  oldprice:"240",
  discountper:20,
  category:"casual",
  collection:"topsellings",
  brand:"zara",
  productimg:"/public/skinyjenns.png",
},
{
  id:7,
  productname:"T-SHIRT WITH TAPE DETAILS",
  rating:"4.3/5",
  price:"192",
  category:"party",
  collection:"topsellings",
  brand:"zara",
  productimg:"/public/skinyjenns.png",
},
{
  id:8,
  productname:"T-SHIRT WITH TAPE DETAILS",
  rating:"4.3/5",
  price:"192",
  category:"formal",
  collection:"topsellings",
  brand:"zara",
  productimg:"/public/skinyjenns.png",
}
]